### ISSUE TITLE
help command doesn't work in macOS

### ISSUE THREAD

**Issue by russelldavis** [plyint/encpass.sh#19]
The `man` command in macOS doesn't support the `-l` option.

```
$ encpass.sh help
man: invalid option -- l
man, version 1.6g

usage: man [-adfhktwW] [section] [-M path] [-P pager] [-S list]
	[-m system] [-p string] name ...
```

**Comment by ahnick** [comment]
@russelldavis Thanks for this.  I had assumed (incorrectly) this was a standard flag across man implementations.  Does macOS use a different flag or is there a typical workaround you are aware of?  If not, then I think I can fallback to stripping the man page formatting and outputting to less.

**Comment by russelldavis** [comment]
Unfortunately I don't see any equivalent flag. I'm guessing there's probably a workaround, but nothing jumps out at me right away. For reference, the manpage is here: https://www.unix.com/man-page/osx/1/man

**Comment by ahnick** [comment]
@russelldavis I just pushed a branch called "help" (https://github.com/plyint/encpass.sh/tree/help) to attempt to emulate what `man` does when the `-l` option is not available.  It should also strip the formatting and directly output to `less` if `man` is missing on the system.

If you have a moment and wouldn't mind pulling the branch down and testing on Mac I'd appreciate it.  Thanks.

**Comment by russelldavis** [comment]
Just tried it, works great! Thanks.

**Comment by ahnick** [comment]
Great, thanks for confirming.  I have pushed to master and published a new release.  Marking as closed.
