### ISSUE TITLE
Command to store password

### ISSUE THREAD

**Issue by nitin194** [plyint/encpass.sh#23]
Hey @ahnick

Thank you for creating such a nice solution. I used it around 1 year ago but forgot how to save password in a bucket or as a standalone. Nor could I find any such direction anywhere. Could you please share commands to create password? Because I only know how to fetch the password

**Comment by ahnick** [comment]
Hey @nitin194.  Glad you like it.  You can access the help anytime by using the command `encpass.sh ?` and it has documentation that should answer your questions on how to create a bucket and add a password to it.  From the command line you can directly add a secret by using the add command and then supplying the password you want to store.

```
encpass.sh add <bucket name> <secret name>
```

Also note that a bucket is automatically created for you if you use the `get_secret` function in your script, but don't specify a bucket name.  Have a look at the [example.sh](https://github.com/plyint/encpass.sh/blob/master/examples/example.sh) file to see some examples on how to use encpass.sh in a script.

Hope that helps.

**Comment by nitin194** [comment]
Hey @ahnick thank you for the suggestion. Yes I was able to add the password in a bucket. Now we are facing other issue that even after executing ./encpass.sh we are facing below error while trying to pull the password by $(get_secret bucket_name secret_name) command

get_secret: command not found

Please suggest?

**Comment by ahnick** [comment]
Make sure the encpass.sh is added to a directory that is in your $PATH variable (e.g. /usr/local/bin/) and then make sure you are sourcing encpass.sh inside your script. 
```
. encpass.sh
```
If you do not source the script before you call the get_secret function then the function will not be found.

**Comment by nitin194** [comment]
Thank you so much @ahnick for your help. I was able to use it properly now
