### ISSUE TITLE
Secrets don't properly get exported on ubuntu 20.04 

### ISSUE THREAD

**Issue by charlieporth1** [plyint/encpass.sh#26]
Secrets don't properly get exported on ubuntu 20.04. I'm having trouble exporting them without having to enter them again on ubuntu. On Both different servers and the same server as root

**Comment by charlieporth1** [comment]
`encpass.sh export bucket` is the command
```
tag version: v4.1.4
SHA256 Checksum: ad153569eda85b17398ca7a3b54333d14e7e73d6f262e1d18ff6164abff35964  /usr/local/bin/encpass.sh```
When I run th `.sh` file for my script for the first time on the second machine it asks for the secret instead of transferring it

**Comment by charlieporth1** [comment]
I'm trying to import with `-p` && `-f` but it thinks -f is the file because you're going off of `$2` or something instead of argument pasring

**Comment by ahnick** [comment]
> `encpass.sh export bucket` is the command

Is your bucket containing the secret literally named "bucket"?  Also, if you are exporting to another machine for the first time you need to make sure you pass the -k option to export the keys.  It will then prompt you for a password to enter to encrypt the archive.  

FYI, if you don't export with the -k or -p option, then the export file will not be encrypted/password protected.  If that is the case, then when you import you need to omit the -p option.

For example, say I have a bucket called "test":
```
$ encpass.sh ls
test
```

and then I export the secrets along with their keys in this bucket...
```
$ encpass.sh export -k test
Exporting keys requires a password to be set for the export file.

Enter Password for export file:
Confirm Password:

Exporting all keys and secrets for bucket test
keys/test
secrets/test/pass.enc
secrets/test/user.enc

Successfully created export file encpass-openssl-2021-08-11-1628705745.tgz.enc in /home/xan/Projects/encpass.sh/test_import//exports
```

Now the export file was created with the .tgz.enc extension (signifying it is an encrypted/password protect compressed archive) and I can move this file to another machine or import it to another folder on the same machine.  When you import the secrets if your file has a .tgz.enc extension then you should pass the -p option.  If the import file just has a .tgz extension, do not specify the -p option as it is not an encrypted/password protected and will cause the script to fail.  

As an example, here I import the exported file from earlier:
```
$ encpass.sh import -f -p /home/xan/Projects/encpass.sh/test_import/exports/encpass-openssl-2021-08-09-1628520470.tgz.enc
Import file: /home/xan/Projects/encpass.sh/test_import/exports/encpass-openssl-2021-08-09-1628520470.tgz.enc
To directory: /home/xan/.encpass

Enter Password for import file:
Confirm Password:
Import successful.
```

And now I can display the secrets
```
$ ep show test
test:
pass = $ecret
user = xan
```

The argument parsing should work fine as long as when you are importing you are only using the -p option for .tgz.enc (encrypted export files).  I do think the error messaging could be improved if the -p option is being used with a .tgz export file to make things clearer.  Hope that helps.

**Comment by charlieporth1** [comment]
I believe I got it working thanks for your help!
 Out of curiosity. I'm using this for a login alert script to hide a secret. Is there a way to make this bucket usable for any user at login?

**Comment by ahnick** [comment]
Great, glad you got it working.

I'm not sure I understand exactly your use case, but I'll try to explain the security model of encpass.sh a bit and let you make your own determination.

As you are probably aware, all keys and secrets are stored under a user's home directory (unless you specified a different location using ENCPASS_HOME_DIR).  If a user has read access to the directory where the key file is stored, then ultimately the user can determine the secret.  (They would just need to apply the same openssl operations the shell script does)  The model is basically the same as how SSH keys work.  (SSH public/private keys are typically stored in ~/.ssh)

Users should either be a part of the team where the team is allowed to know all secrets in a bucket or users should each have their own bucket that is stored in their home directory or a directory that is only accessible to their user.

**Comment by charlieporth1** [comment]
I pretty much want it so the secrets are encrypted but anyone can read the secrets so that if I have a login for a user that it can alert me without having to set up secrets for said user or a new user. Is there a security issue with that other than the global read operation? Is there a way to allow only users that have ssh access and the ability to login via ssh to access a secret and thus execute this program which would alert me that they logged in to the server

**Comment by ahnick** [comment]
From your explanation, it sounds like you have a group of authenticated users that are logging into a server via ssh and then you want your script to be able to access the shared secrets for these users.  There should be no security issues with this assuming these users are allowed to know the shared secrets.

Assuming I have understood the scenario properly, then all you need to do is to make sure the users are in a common group (call it sshusers or whatever you want) and can read a shared folder and then point encpass.sh to that shared folder by setting the ENCPASS_HOME_DIR environment variable upon login for each user.  If you don't want the users within the group to be able to update the shared secrets, then make sure the ownership permissions of the directory are set to read/write for just your administrative user and read for the group of users.

**Comment by charlieporth1** [comment]
Thanks for your help!
