### ISSUE TITLE
How to use in MacOS

### ISSUE THREAD

**Issue by tjx666** [plyint/encpass.sh#28]
I install it by:

```sh
curl https://raw.githubusercontent.com/ahnick/encpass.sh/master/encpass.sh -o /usr/local/bin/encpass.sh
```

Every I using it ask me permission, after I give it permission, it still doesn't work.

<img width="977" alt="image" src="https://user-images.githubusercontent.com/41773861/196054174-8e63c116-4734-4542-a3cc-73cf95b7c4e2.png">

**Comment by tjx666** [comment]
Is because I need to to execute permission?

<img width="946" alt="image" src="https://user-images.githubusercontent.com/41773861/196054271-c7da80ef-c3d7-4742-8005-4be069277ab6.png">

**Comment by ahnick** [comment]
You'll need to give your user executable permissions on the encpass.sh script if it doesn't already have them.

`$ sudo chown 755 /usr/local/bin/encpass.sh`

**Comment by ahnick** [comment]
> Is because I need to to execute permission?
> 
> <img alt="image" width="946" src="https://user-images.githubusercontent.com/41773861/196054271-c7da80ef-c3d7-4742-8005-4be069277ab6.png">

Yes. I need to update the installation instructions to include these steps. :)

**Comment by tjx666** [comment]
@ahnick Thanks, It works now
